### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by PlatyPew** [DISMGryphons/GryphonCTF2017-Challenges#2]
Please do note that at https://github.com/DISMGryphons/GryphonCTF2017-Challenges/tree/master/challenges/misc/Hell's%20Programmer#name-of-challenge, the "Name of Challenge" should be changed to "Hell's Programmer".

This mistake was noted after the deadline.
Please mend accordingly.
Thanks.

**Comment by bitxer** [comment]
Hi PlatyPooper,

Thank you for bringing the issue up to us. The necessary changes have been made in commit 83099d1.
